DROP TABLE IF EXISTS user;
DROP TABLE IF EXISTS leaderboard;

CREATE TABLE user (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  username TEXT UNIQUE NOT NULL,
  password TEXT NOT NULL
);

Create TABLE leaderboard(
 username TEXT NOT NULL,
 score INTEGER
);