DROP TABLE IF EXISTS user;
DROP TABLE IF EXISTS leaderboard;

CREATE TABLE user (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  username TEXT UNIQUE NOT NULL,
  password TEXT NOT NULL
);

Create TABLE leaderboard(
 userId INTEGER NOT NULL,
 score INTEGER NOT NULL,
 wins INTEGER NOT NULL,
 losses INTEGER NOT NULL,
 ties INTEGER NOT NULL
);  